# Generated by Django 6.1.1 on 2026-09-30 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetguard', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transfer_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assetguard.equipmenttype')),
                ('from_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='assetguard.base')),
                ('to_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='assetguard.base')),
            ],
        ),
    ]
