# Generated by Django 6.1.1 on 2026-09-30 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetguard', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='assetguard.base'),
        ),
    ]
